In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
import keras
from tensorflow import keras
from tensorflow.keras import layers
import copy
from copy import deepcopy
from keras.utils import to_categorical

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
X=pd.read_csv('/content/drive/MyDrive/diab_clean_version.csv')
X.head()

Unnamed: 0             race  gender      age admission_type_id  \
0           1        Caucasian  Female  [10-20)         Emergency   
1           2  AfricanAmerican  Female  [20-30)         Emergency   
2           3        Caucasian    Male  [30-40)         Emergency   
3           4        Caucasian    Male  [40-50)         Emergency   
4           5        Caucasian    Male  [50-60)        Other type   

  discharge_disposition_id admission_source_id  time_in_hospital  \
0                     Home      Emergency Room                 3   
1                     Home      Emergency Room                 2   
2                     Home      Emergency Room                 2   
3                     Home      Emergency Room                 1   
4                     Home        Other source                 3   

   num_lab_procedures  num_procedures  ...  number_emergency  \
0                  59               0  ...                 0   
1                  11               5  ...                 0   
2                  44               1  ...                 0   
3                  51               0  ...                 0   
4                  31               6  ...                 0   

   number_inpatient  diag_1  number_diagnoses max_glu_serum  a1cresult  \
0                 0      No                 9          None       None   
1                 1      No                 6          None       None   
2                 0      No                 7          None       None   
3                 0      No                 5          None       None   
4                 0      No                 9          None       None   

  insulin change diabetesmed readmitted  
0      Up     Ch         Yes        >30  
1      No     No         Yes         NO  
2      Up     Ch         Yes         NO  
3  Steady     Ch         Yes         NO  
4  Steady     No         Yes        >30  

[5 rows x 22 columns]

In [ ]:
X.shape

(98052, 22)

In [ ]:
rows_to_be_removed=[]
for i in range(len(X['readmitted'])):
  if(X.iloc[i]['readmitted']=='NO'):
    rows_to_be_removed.append(i)


In [ ]:
len(rows_to_be_removed)

52337

In [ ]:
X.drop(rows_to_be_removed,inplace=True)

In [ ]:
X.shape

(45715, 22)

In [ ]:
X['readmitted'].value_counts()

>30    34649
<30    11066
Name: readmitted, dtype: int64

In [ ]:
y=[]
for ele in X['readmitted']:
  if(ele=='>30'):
    y.append(1)
  else:
    y.append(0)

In [ ]:
X.shape

(45715, 22)

In [ ]:
X=X.drop(['readmitted'],axis=1)

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=40000, test_size=5714,random_state=42)

In [ ]:
X_train.shape

(40000, 21)

In [ ]:
# train_labels = to_categorical(y_train, dtype ="uint8")
# test_labels = to_categorical(y_test, dtype ="uint8")

In [ ]:
train_labels.shape

(40000, 2)

In [ ]:
X.columns

Index(['Unnamed: 0', 'race', 'gender', 'age', 'admission_type_id',
       'discharge_disposition_id', 'admission_source_id', 'time_in_hospital',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'number_diagnoses', 'max_glu_serum', 'a1cresult', 'insulin', 'change',
       'diabetesmed'],
      dtype='object')

## One Hot encoding the categorical Variables and Standardising the numerical features

In [ ]:
X['diabetesmed'].value_counts()

Yes    36415
No      9300
Name: diabetesmed, dtype: int64

In [ ]:
train_race=X_train['race'].to_numpy()
test_race=X_test['race'].to_numpy()
onenc_quantity=OneHotEncoder()
onenc_train=onenc_quantity.fit(train_race.reshape(-1,1))
train_race=onenc_quantity.transform(train_race.reshape(-1,1)).toarray()
test_race=onenc_quantity.transform(test_race.reshape(-1,1)).toarray()

In [ ]:
print(train_race[:200])

[[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0.

In [ ]:
train_gender=X_train['gender'].to_numpy()
test_gender=X_test['gender'].to_numpy()
onenc_quantity=OneHotEncoder()
onenc_train=onenc_quantity.fit(train_gender.reshape(-1,1))
train_gender=onenc_quantity.transform(train_gender.reshape(-1,1)).toarray()
test_gender=onenc_quantity.transform(test_gender.reshape(-1,1)).toarray()

In [ ]:
print(train_gender)

[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [1. 0.]
 [1. 0.]]


In [ ]:
train_diag=X_train['diag_1'].to_numpy()
test_diag=X_test['diag_1'].to_numpy()
onenc_quantity=OneHotEncoder()
onenc_train=onenc_quantity.fit(train_diag.reshape(-1,1))
train_diag=onenc_quantity.transform(train_diag.reshape(-1,1)).toarray()
test_diag=onenc_quantity.transform(test_diag.reshape(-1,1)).toarray()

In [ ]:
print(train_diag)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [1. 0.]]


In [ ]:
train_diabetes=X_train['diabetesmed'].to_numpy()
test_diabetes=X_test['diabetesmed'].to_numpy()
onenc_quantity=OneHotEncoder()
onenc_train=onenc_quantity.fit(train_diabetes.reshape(-1,1))
train_diabetes=onenc_quantity.transform(train_diabetes.reshape(-1,1)).toarray()
test_diabetes=onenc_quantity.transform(test_diabetes.reshape(-1,1)).toarray()



In [ ]:
print(train_diabetes)

[[1. 0.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 0.]
 [0. 1.]
 [1. 0.]]


In [ ]:
X['age'].value_counts()

[70-80)     12267
[60-70)     10195
[80-90)      8098
[50-60)      7442
[40-50)      4189
[30-40)      1550
[90-100)     1092
[20-30)       673
[10-20)       195
[0-10)         14
Name: age, dtype: int64

In [ ]:
age={'[70-80)':0,'[60-70)':1,'[80-90)':2,'[50-60)':3,'[40-50)':4,'[30-40)':5,'[90-100)':6,'[20-30)':7,'[10-20)':8,'[0-10)':9}
age
glu_serum={'None':0,'Norm':1,'>200':2,'>300':3}
glu_serum
a1c_result={'None':0,'Norm':1,'>7':2,'>8':3}



In [ ]:
train_age=np.array([age[ele] for ele in X_train['age']])
test_age=np.array([age[ele] for ele in X_test['age']])
scaler = StandardScaler()
scaler.fit(train_age.reshape(-1, 1))
train_age=scaler.transform(train_age.reshape(-1,1))
test_age=scaler.transform(test_age.reshape(-1,1))

In [ ]:
print(train_age)

[[ 0.63924158]
 [-0.50828061]
 [ 1.78676378]
 ...
 [ 1.78676378]
 [-1.08204171]
 [ 2.36052488]]


In [ ]:
scaler = StandardScaler()
train_time=X_train['time_in_hospital'].to_numpy()
test_time=X_test['time_in_hospital'].to_numpy()
scaler.fit(train_time.reshape(-1, 1))
train_time=scaler.transform(train_time.reshape(-1,1))
test_time=scaler.transform(test_time.reshape(-1,1))

In [ ]:
print(train_time)

[[-0.52352545]
 [ 0.80847327]
 [-1.18952481]
 ...
 [-0.52352545]
 [ 0.47547359]
 [ 0.47547359]]


In [ ]:
train_lab=X_train['num_lab_procedures'].to_numpy()
test_lab=X_test['num_lab_procedures'].to_numpy()
scaler.fit(train_lab.reshape(-1, 1))
train_lab=scaler.transform(train_lab.reshape(-1,1))
test_lab=scaler.transform(test_lab.reshape(-1,1))

In [ ]:
print(train_lab)

[[-0.61011222]
 [ 0.62055753]
 [-0.25116688]
 ...
 [ 0.56927962]
 [-0.25116688]
 [ 1.13333659]]


In [ ]:
train_process=X_train['num_procedures'].to_numpy()
test_process=X_test['num_procedures'].to_numpy()
scaler.fit(train_process.reshape(-1, 1))
train_process=scaler.transform(train_process.reshape(-1,1))
test_process=scaler.transform(test_process.reshape(-1,1))

In [ ]:
print(train_process)

[[-0.7601184 ]
 [-0.15841378]
 [-0.7601184 ]
 ...
 [-0.7601184 ]
 [-0.7601184 ]
 [-0.7601184 ]]


In [ ]:
train_med=X_train['num_medications'].to_numpy()
test_med=X_test['num_medications'].to_numpy()
scaler.fit(train_med.reshape(-1, 1))
train_med=scaler.transform(train_med.reshape(-1,1))
test_med=scaler.transform(test_med.reshape(-1,1))

train_out=X_train['number_outpatient'].to_numpy()
test_out=X_test['number_outpatient'].to_numpy()
scaler.fit(train_out.reshape(-1, 1))
train_out=scaler.transform(train_out.reshape(-1,1))
test_out=scaler.transform(test_out.reshape(-1,1))

train_in=X_train['number_inpatient'].to_numpy()
test_in=X_test['number_inpatient'].to_numpy()
scaler.fit(train_in.reshape(-1, 1))
train_in=scaler.transform(train_out.reshape(-1,1))
test_out=scaler.transform(test_out.reshape(-1,1))

train_emergency=X_train['number_emergency'].to_numpy()
test_emergency=X_test['number_emergency'].to_numpy()
scaler.fit(train_emergency.reshape(-1, 1))
train_emergency=scaler.transform(train_emergency.reshape(-1,1))
test_emergency=scaler.transform(test_emergency.reshape(-1,1))

train_diagnoses=X_train['number_diagnoses'].to_numpy()
test_diagnoses=X_test['number_diagnoses'].to_numpy()
scaler.fit(train_diagnoses.reshape(-1, 1))
train_diagnoses=scaler.transform(train_diagnoses.reshape(-1,1))
test_diagnoses=scaler.transform(test_diagnoses.reshape(-1,1))

train_glu=np.array([glu_serum[ele] for ele in X_train['max_glu_serum']])
test_glu=np.array([glu_serum[ele] for ele in X_test['max_glu_serum']])
scaler = StandardScaler()
scaler.fit(train_glu.reshape(-1, 1))
train_glu=scaler.transform(train_glu.reshape(-1,1))
test_glu=scaler.transform(test_glu.reshape(-1,1))

train_a1c=np.array([a1c_result[ele] for ele in X_train['a1cresult']])
test_a1c=np.array([a1c_result[ele] for ele in X_test['a1cresult']])
scaler = StandardScaler()
scaler.fit(train_a1c.reshape(-1, 1))
train_a1c=scaler.transform(train_a1c.reshape(-1,1))
test_a1c=scaler.transform(test_a1c.reshape(-1,1))



In [ ]:
insulin_={'Down':1,"No":0,'Steady':2,'Up':3}
train_insulin = np.array([insulin_[ele] for ele in X_train['insulin']])
test_insulin = np.array([insulin_[ele] for ele in X_test['insulin']])
scaler = StandardScaler()
scaler.fit(train_a1c.reshape(-1, 1))
train_insulin=scaler.transform(train_insulin.reshape(-1,1))
test_insulin=scaler.transform(test_insulin.reshape(-1,1))


In [ ]:
print(train_insulin)

[[4.45865567e-17]
 [2.00000000e+00]
 [2.00000000e+00]
 ...
 [4.45865567e-17]
 [1.00000000e+00]
 [4.45865567e-17]]


In [ ]:
admission_type_id={'Emergency':2,'Other type':0}
train_add_id = np.array([admission_type_id[ele] for ele in X_train['admission_type_id']])
test_add_id = np.array([admission_type_id[ele] for ele in X_test['admission_type_id']])
scaler = StandardScaler()
scaler.fit(train_a1c.reshape(-1, 1))
train_add_id=scaler.transform(train_add_id.reshape(-1,1))
test_add_id=scaler.transform(test_add_id.reshape(-1,1))

In [ ]:
print(train_add_id)

[[2.00000000e+00]
 [2.00000000e+00]
 [4.45865567e-17]
 ...
 [2.00000000e+00]
 [4.45865567e-17]
 [2.00000000e+00]]


In [ ]:
train_data=np.column_stack((train_race,train_gender,train_add_id,train_diag,train_diabetes,train_age,train_time,train_lab,train_process,train_med,train_in,train_out,train_emergency,train_diagnoses,train_glu,train_a1c,train_insulin))
test_data=np.column_stack((test_race,test_gender,test_add_id,test_diag,test_diabetes,test_age,test_time,test_lab,test_process,test_med,test_in,test_out,test_emergency,test_diagnoses,test_glu,test_a1c,test_insulin))

In [ ]:
train_data.shape

(40000, 24)

In [ ]:
np.save('train_data',train_data)
np.save('test_data',test_data)
np.save('y_train',y_train)
np.save('y_test',y_test)

In [ ]:
result=np.load('train_data.npy')
result.shape

(34285, 22)